In [4]:
import numpy

array1 =numpy.array([
              
              [1,2,3,4,5],
              [5,6,7,8,9]
])

print(array1)

[[1 2 3 4 5]
 [5 6 7 8 9]]


In [8]:
import numpy

array1 =numpy.array([
              
              [1,2,3,4,5],
              [5,6,7,8,9]
])

print(array1.dtype)
print(array1.ndim)
print(array1.shape)
print(array1.size)

int32
2
(2, 5)
10


In [9]:
from numpy import * 

array1 =array([
              
              [1,2,3,4,5],
              [5,6,7,8,9]
])

print(array1)

[[1 2 3 4 5]
 [5 6 7 8 9]]


In [22]:
from numpy import * 

array1 =array([
              
              [1,2,3,4,5,6],
              [5,6,7,8,9,5]
])

array2 = array1.flatten()            # flatten() is used to make it one dimensional
print("One dimensional form : ",array2)


array3= array2.reshape(3,4)          # make it two dimensional
print("Two dimensional form : ",array3)


array4 = array2.reshape(2,2,3)        # make it three dimensional
print ("Three dimensional form : ",array4)

array5=array4.ndim
print("Dimension is : " ,array5)      # check its dimension

One dimensional form :  [1 2 3 4 5 6 5 6 7 8 9 5]
Two dimensional form :  [[1 2 3 4]
 [5 6 5 6]
 [7 8 9 5]]
Three dimensional form :  [[[1 2 3]
  [4 5 6]]

 [[5 6 7]
  [8 9 5]]]
Dimension is :  3


In [19]:
from numpy import * 

array1 =array([
              
              [1,2,3,4,5],
              [5,6,7,8,9]
])

array2 = array1.flatten()            # flatten() is used to make it one dimensional
print(array2)


array3= array2.reshape(2,5)          # make it two dimensional
print(array3)


array4 = array2.reshape(1,2,5)        # make it three dimensional
print (array4)

array5=array4.ndim
print("Dimension is : " ,array5)      # check its dimension

[1 2 3 4 5 5 6 7 8 9]
[[1 2 3 4 5]
 [5 6 7 8 9]]
[[[1 2 3 4 5]
  [5 6 7 8 9]]]
Dimension is :  3
