In [2]:
from numpy import *

m1 = ([1,2,3],
      [4,5,6],
      [7,8,9]
     )


m2 = ([4,5,6],
      [1,2,3],
      [2,3,5]
     )

result = m1+m2
print(result)

([1, 2, 3], [4, 5, 6], [7, 8, 9], [4, 5, 6], [1, 2, 3], [2, 3, 5])


In [12]:
from numpy import *

m1 = [[1,2,3],
      [4,5,6],
      [7,8,9]
     ]


m2 = [[4,5,6],
      [1,2,3],
      [2,3,5]
     ]

result = add(m1,m2)
print(result)



[[ 5  7  9]
 [ 5  7  9]
 [ 9 11 14]]


In [13]:
from numpy import *

m1 = [[1,2,3],
      [4,5,6],
      [7,8,9]
     ]


m2 = [[4,5,6],
      [1,2,3],
      [2,3,5]
     ]

result = subtract(m1,m2)
print(result)



[[-3 -3 -3]
 [ 3  3  3]
 [ 5  5  4]]


In [14]:
from numpy import *

m1 = [[1,2,3],
      [4,5,6],
      [7,8,9]
     ]


m2 = [[4,5,6],
      [1,2,3],
      [2,3,5]
     ]

result = dot(m1,m2)               # to multiply dot is used
print(result)



[[ 12  18  27]
 [ 33  48  69]
 [ 54  78 111]]


In [9]:

matrix = [
          [1,2,3],
          [2,3,4],
          [3,4,5]
         ]

print(matrix[0][2])
print(matrix[1][2])
print(matrix[2][2])

3
4
5


In [10]:
# by changing value of any element


matrix = [
          [1,2,3],
          [2,3,4],
          [3,4,5]
         ]

matrix[0][2] = 10
print(matrix[0][2])

10


In [11]:
# using nested loop matrix can be expressed

matrix = [
          [1,2,3],
          [2,3,4],
          [3,4,5]
         ]

for row in matrix :
    for column in row :
        print(column)

1
2
3
2
3
4
3
4
5
